crds:
  enabled: true
  upgradeJob:
    enabled: true

grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: prometheus
    hosts:
    - prometheus.${DOMAIN}
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-sc
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 8Gi
    nodeSelector:
      size: m
    enableRemoteWriteReceiver: true
