server:
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: prometheus
    hosts:
    - prometheus.${DOMAIN}
  persistentVolume:
    existingClaim: prometheus-data
  extraArgs:
    web.enable-remote-write-receiver: ""
  nodeSelector:
    size: m

prometheus-pushgateway:
  enabled: true
  nodeSelector:
    size: m
