apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: alloy
  repo: https://grafana.github.io/helm-charts
  version: 1.1.1
  releaseName: alloy
  namespace: monitoring
  valuesFile: values.yaml
