apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: alloy
  repo: https://grafana.github.io/helm-charts
  version: 10.1.2
  releaseName: grafana
  namespace: monitoring
  valuesFile: values.yaml
