---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: telegraf-ids-secrets
  namespace: monitoring
spec:
  encryptedData:
    influxdb-telegraf-ids-token: AgCQzWNWpUaTZ+SB4/Hm6NLhjIeTqtfTVL2xU6BeTopwVa9PBwNtMI1swr/NCZnyzf6lbqce5Un/K02+ijuT+Gh4YFOKgu3GxiV72e2b6WCbLer8MzQF1FgvHpMsParT1k/2+Zx/5a9ItrZynt8GUe4GMmw2xO8/MLU6wFrerfuv2ywcNdw1+0HK2yEu8IfLEHbqHvkaitgA3IHGHDVE4zazEEHjQtfseO3h1KXSAdPPbFLNP6oOg0OhWEvaZdaS5UahAbjz01ZrZv6qFkjTmB/7lpoh/GBWRPH6TVO1448tY+eFosC/qtapPdhQck6KdXzfZxkHIQJOSSzqAuAbMpaz8EM1JYcLn2TFIZYnenwywONlM4RziR4KIzj6moIrT3pKsB5MrgBStnO1xnWJ4DOcjPJDi92xSg7BD5iX9wBqvHSzUzXf/PZ8CqlDbO2Dt8PBPZD9jLdyIRTDXSlbWGUx941pfdOqj8u2yl7g12NRq7tfDXBsoeCx+G1Bf//Cwvk0grZZxRQDeBtq0d6xsAoCPi7jKqvXiC3I0bO0dd3CDLQcBVPbkpriAhKM3kZ2ErJuySM/+CKaRvmHVhBRVAPVwtk1rHa9ApseM35YY+Uql84DnVFiSb8qhwjssu93xhJFf/Z6AhDnuWcQRkFPqoMth1atO3C8Uq/EvRy6rcZo23WmE7+9JudYoMNkG4mD0Rj3+GCSTakYDholSv77hT9PGPg0KWjO00tWP80bVTk0Zovg9O7p5Q7YsI+fNnJk6HQNQxiC72BTiK2fZmxdJnT8FEeirS4BBNtGZ25Bborp97/LyFeA98KZ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: telegraf-ids-secrets
      namespace: monitoring
    type: Opaque
