apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-ids-config
  namespace: monitoring
data:
  telegraf.conf: |
    [agent]
      hostname = "${HOSTNAME}"
      interval = "60s"
      round_interval = true
      debug = true
      quiet = false

    [[inputs.tail]]
      name_override = "ids_alerts"
      files = ["/var/log/suricata/eve.json"]
      from_beginning = false
      data_format = "json"
      json_string_fields = [
        "event_type",
        "src_ip",
        "dest_ip",
        "in_iface",
        "proto",
        "pkt_src",
        "alert_action",
        "alert_signature",
        "alert_category",
        "http_hostname",
        "http_http_method",
        "http_uri",
        "http_user_agent",
        "app_proto",
        "direction"
      ]

    [[processors.starlark]]
      namepass = ["ids_alerts"]
      source = '''
    def apply(metric):
        if metric.fields["event_type"] == "alert":
            return metric
        return None
    '''

    [[processors.converter]]
      namepass = ["ids_alerts"]
      [processors.converter.fields]
        string = [
          "src_ip",
          "dest_ip",
          "in_iface",
          "proto",
          "pkt_src",
          "alert_action",
          "alert_signature",
          "alert_category",
          "http_hostname",
          "http_http_method",
          "http_uri",
          "http_user_agent",
          "app_proto",
          "direction"
        ]

    [[inputs.tail]]
      name_override = "ids_stats"
      files = ["/var/log/suricata/eve.json"]
      from_beginning = false
      data_format = "json"
      json_string_fields = ["event_type"]

    [[processors.starlark]]
      namepass = ["ids_stats"]
      source = '''
    def apply(metric):
        if metric.fields["event_type"] == "stats":
            return metric
        return None
    '''

    [[processors.converter]]
      namepass = ["ids_stats"]
      [processors.converter.fields]
        string = ["event_type"]

    [[inputs.tail]]
      name_override = "ids_http"
      files = ["/var/log/suricata/eve.json"]
      from_beginning = false
      data_format = "json"
      json_string_fields = ["event_type"]

    [[processors.starlark]]
      namepass = ["ids_http"]
      source = '''
    def apply(metric):
        if metric.fields["event_type"] == "http":
            return metric
        return None
    '''

    [[processors.converter]]
      namepass = ["ids_http"]
      [processors.converter.fields]
        string = ["event_type"]

    [[outputs.influxdb_v2]]
      urls = ["https://influxdb.${DOMAIN}"]
      token = "${INFLUXDB_TOKEN}"
      organization = "krieg"
      bucket = "ids-metrics"
