apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-ids
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: telegraf-ids
  template:
    metadata:
      labels:
        name: telegraf-ids
    spec:
      containers:
      - name: telegraf-ids
        image: telegraf:1.34.4
        env:
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegraf-ids-secrets
              key: influxdb-telegraf-ids-token
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
          readOnly: true
        - name: suricata-logs
          mountPath: /var/log/suricata
      volumes:
      - name: config
        configMap:
          name: telegraf-ids-config
      - name: suricata-logs
        persistentVolumeClaim:
          claimName: suricata-logs
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "node-s"
        effect: "NoSchedule"
