apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: suricata-logs
  namespace: monitoring
spec:
  storageClassName: nfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
