apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-config
  namespace: monitoring
data:
  suricata.yaml: |
    %YAML 1.1
    ---
    # Interfaz a monitorear
    af-packet:
    - interface: eth0
      cluster-id: 99
      cluster-type: cluster_flow
      defrag: yes
      use-mmap: yes
      ring-size: 200000
      block-size: 1048576
      buffer-size: 65536
      max-pending-packets: 1024
      checksum-checks: auto

    # Registros
    outputs:
    - fast:
        enabled: yes
        filename: fast.log
    - eve-log:
        enabled: yes
        filetype: regular
        filename: eve.json
        types:
        - alert:
            payload: yes
            metadata: yes
            tags: yes
            packet: yes
        - dns:
        - http:
        - tls:
        - ssh:
        - smtp:
        - stats:
            totals: yes
            threads: yes
    - stats:
        enabled: yes
        filename: stats.log
        interval: 60

    # Detección
    detect-engine:
      - profile: medium
        custom-values:
          toclient-groups: 3
          toserver-groups: 3

    logging:
      default-log-level: notice
      outputs:
      - console:
          enabled: yes
      - file:
          enabled: yes
          filename: /var/log/suricata/suricata.log
          level: info

    # Archivo de reglas
    default-rule-path: /etc/suricata/rules
    rule-files:
    - suricata.rules

    # Red local (ajusta según tu red LAN)
    vars:
      address-groups:
        HOME_NET: "[192.168.0.0/16]"

    # Otros ajustes
    stats:
      enabled: yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-threshold-config
  namespace: monitoring
data:
  threshold.config: |
    # Thresholding configuration
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-classification-config
  namespace: monitoring
data:
  classification.config: |
    # classification.config
    config classification: attempted-admin,Attempted Administrator Privilege Gain,1
    config classification: successful-admin,Successful Administrator Privilege Gain,2
    config classification: attempted-user,Attempted User Privilege Gain,3
    config classification: successful-user,Successful User Privilege Gain,4
    config classification: attempted-dos,Attempted Denial of Service,5
    config classification: successful-dos,Successful Denial of Service,6
    config classification: trojan-activity,A Network Trojan was detected,7
    config classification: misc-activity,Miscellaneous activity,8
    config classification: unknown,Unknown Traffic,9
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-reference-config
  namespace: monitoring
data:
  reference.config: |
    # reference.config
    config reference: cve https://cve.mitre.org/cgi-bin/cvename.cgi?name=%s
    config reference: url http://%s
    config reference: bugtraq http://www.securityfocus.com/bid/%s
    config reference: urlhaus https://urlhaus.abuse.ch/url/%s/
