apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-config
  namespace: monitoring
data:
  suricata.yaml: |
    %YAML 1.1
    ---
    af-packet:
    - interface: eth0
      cluster-id: 99
      cluster-type: cluster_flow
      defrag: yes
      use-mmap: yes
      ring-size: 200000
      block-size: 1048576
      buffer-size: 65536
      max-pending-packets: 1024
      checksum-checks: auto

    outputs:
    - fast:
        enabled: yes
        filename: fast.log
    - eve-log:
        enabled: yes
        filetype: regular
        filename: eve.json
        types:
        - alert:
            payload: yes
            metadata: yes
            tags: yes
            packet: yes
        - dns:
        - http:
        - tls:
        - ssh:
        - smtp:
        - stats:
            totals: yes
            threads: yes
    - stats:
        enabled: yes
        filename: stats.log
        interval: 60

    # Detección
    detect-engine:
      - profile: medium
        custom-values:
          toclient-groups: 3
          toserver-groups: 3

    logging:
      default-log-level: notice
      outputs:
      - console:
          enabled: yes
      - file:
          enabled: yes
          filename: /var/log/suricata/suricata.log
          level: info

    default-rule-path: /var/lib/suricata/rules
    rule-files:
    - suricata.rules

    vars:
      address-groups:
        HOME_NET: "[192.168.0.0/16]"

    stats:
      enabled: yes
