server:
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: nfs-sc
  extraArgs:
    web.enable-remote-write-receiver: ""
  resources:
    requests:
      cpu: 250m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  nodeSelector:
    size: m

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus-pushgateway:
  enabled: false
