{
 "title": "Network alerts",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "measurement",
    "label": "Measurement",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.measurements(bucket: \"${bucket}\")\r\n"
    }
   },
   { "name": "bucket", "label": "Bucket", "query": "ids-metrics" }
  ]
 },
 "panels": [
  {
   "title": "Top Alert Signature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"alert_signature\")\r\n  |> experimental.mode()\r\n  |> yield(name: \"most_repeated_value\")\r\n"
    }
   ]
  },
  {
   "title": "Top Alert Category",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"alert_category\")\r\n  |> experimental.mode()\r\n  |> yield(name: \"most_repeated_value\")\r\n"
    }
   ]
  },
  {
   "title": "Top Source IP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"experimental\"\r\n\r\nfrom(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"src_ip\" and r[\"_value\"] != \"\")\r\n  |> experimental.mode()\r\n  |> yield(name: \"most_repeated_value\")\r\n"
    }
   ]
  },
  {
   "title": "Port source",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"src_port\")\r\n  |> duplicate(column: \"_value\", as: \"src_port\")\r\n  |> group(columns: [\"src_port\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"proto\")\r\n  |> duplicate(column: \"_value\", as: \"proto\")\r\n  |> group(columns: [\"proto\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Port destination",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"dest_port\")\r\n  |> duplicate(column: \"_value\", as: \"dest_port\")\r\n  |> group(columns: [\"dest_port\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "IP source",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"src_ip\")\r\n  |> duplicate(column: \"_value\", as: \"src_ip\")\r\n  |> group(columns: [\"src_ip\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Alert signature",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"alert_signature\")\r\n  |> duplicate(column: \"_value\", as: \"alert_signature\")\r\n  |> group(columns: [\"alert_signature\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Alert category",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"alert_category\")\r\n  |> duplicate(column: \"_value\", as: \"alert_category\")\r\n  |> group(columns: [\"alert_category\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "IP destination",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == ${measurement:doublequote} and r._field == \"dest_ip\")\r\n  |> duplicate(column: \"_value\", as: \"dest_ip\")\r\n  |> group(columns: [\"dest_ip\"])\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Alert signatures",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"alert_signature\")\r\n  |> duplicate(column: \"_value\", as: \"alert_signature\")\r\n  |> group(columns: [\"alert_signature\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\r\n"
    }
   ]
  },
  {
   "title": "Alert Severity type 1",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"alert_severity\" and r[\"_value\"] == 1)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\r\n  |> yield(name: \"count\")\r\n"
    }
   ]
  },
  {
   "title": "Alert Severity type 2",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"alert_severity\" and r[\"_value\"] == 2)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count)\r\n  |> yield(name: \"count\")\r\n"
    }
   ]
  },
  {
   "title": "Alert Severity type 3",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote} and r[\"_field\"] == \"alert_severity\" and r[\"_value\"] == 3)\r\n  |> aggregateWindow(every: 10m, fn: count)\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == ${measurement:doublequote})\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"alert_signature_id\", \"alert_signature\", \"src_ip\", \"src_port\", \"proto\", \"dest_ip\", \"dest_port\", \"app_proto\", \"alert_action\", \"alert_severity\"])\r\n  |> sort(columns: [\"_time\"], desc: true)\r\n  |> top(n: 2000)\r\n  |> rename(columns: {_time: \"Time\", alert_signature_id: \"Signature ID\", alert_signature: \"Alert Signature\", src_ip: \"Source IP\", src_port: \"Source port\", proto: \"Protocol\", dest_ip: \"Destination IP\", dest_port: \"Destination port\", app_proto: \"App protocol\", alert_action: \"Action\", alert_severity: \"Severity\"})\r\n"
    }
   ]
  }
 ]
}