apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  ports:
  - name: http-grafana
    port: 3000
    targetPort: http-grafana
    protocol: TCP
  selector:
    app: grafana
  type: ClusterIP
