apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  annotations:
    avp.kubernetes.io/path: "secret/data/monitoring/grafana"
type: Opaque
stringData:
  admin-user: <username>
  admin-password: <password>
