image:
  repository: influxdb
  tag: 2.7.11-alpine
adminUser:
  organization: "krieg"
  existingSecret: influxdb-secrets
persistence:
  enabled: true
  useExisting: true
  name: influxdb-data
  mountPath: /var/lib/influxdb2
ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hostname: influxdb.${DOMAIN}
tolerations:
- key: "role"
  operator: "Equal"
  value: "node-m"
  effect: "NoSchedule"
