apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-nfs1
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      name: telegraf-nfs1
  template:
    metadata:
      labels:
        name: telegraf-nfs1
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: telegraf-nfs1
        image: msd117/telegraf-snmp:0.0.3
        env:
        - name: NAS1_HOST
          valueFrom:
            secretKeyRef:
              name: telegraf-nfs1-secrets
              key: nas1-host
        - name: SNMP_USERNAME
          valueFrom:
            secretKeyRef:
              name: telegraf-nfs1-secrets
              key: snmp-username
        - name: SNMP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: telegraf-nfs1-secrets
              key: snmp-password
        - name: SNMP_PRIVACY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: telegraf-nfs1-secrets
              key: snmp-privacy-password
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegraf-nfs1-secrets
              key: influxdb-telegraf-nfs1-token
        volumeMounts:
        - name: config
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: telegraf-nfs1-config
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "node-s"
        effect: "NoSchedule"
