apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
  namespace: monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: create-credentials
        image: influxdb:${INFLUXDB_VERSION}
        command: ["/bin/sh", "-c"]
        args:
        - |
          influx setup \
            --host https://influxdb.${DOMAIN} \
            --bucket telegraf-metrics \
            --org krieg \
            --password "${INFLUXDB_OPERATOR_PASSWORD}" \
            --username admin \
            --token "${INFLUXDB_OPERATOR_TOKEN}" \
            --force
        envFrom:
        - secretRef:
            name: influxdb-secrets
