---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: influxdb-secrets
  namespace: monitoring
spec:
  encryptedData:
    operator-token: AgA3aIALVQtJBz6aQo2PYiRI5TFlUbpYzVBwQQYtD2OXdjsTVlPJ2T3Bf9dVc29xRIVb+b7nReADsRy8DwadJMWMc6Hwh6BNekHGxULrn0Go8mPwSEcxp7fg/ASxxjegJvQmjcj/6jeMHS9KLtyQY8zqE0E4pJHWzIpKpKOS3gLOkRrss9noI4Suzm9mC383nm396IYUYNtKP7/5trc935glp5OLqHSWNOnmZpLiex7w6C2d4HRRQeKKk6L07RosE/2z9f/cFnuB/jaeYsynxUDHnGLhQfmZkA+jvKT1dcZ1ox8nFKfefvXx2kU9gNldUswiyrokjP9rNbordI3y3t4soS25kedjgfv/Ahw4dLRWO2K8Jm8usfoLS5HLHictSJ6o3Yt/Tu/tf7civycVzhiwdffDluUMcLG9UGSYmHeiTr/hseTdyQrlm9r5bQMuePRXKekrv5Q/4P3dGcMuGPJ7R08RsL0/k7aNXsmGGDSPJL6TsPGjzeMVpwpO0pDhQhPz0Hqtn9H60qUOubStKG3UyHYpXtGUW1gy7m3tW5lqAM656qHiSrwmjpjdHrLjVe1KSXCoWYGPt2xttzn3q6Jwqlv+cl7XcLbu4KrAGMXl+JE/JiOasJzMqeboRf8M3jc/oA1GY03WovPieP35UfuNSkND51Za6FvM7o56Njco3LpTQLPXR0yZ6pw0r5Zxihqk3x3wNSnne8uIE+NpiiS0dwSLFFB0Ivi/Tf4v46hy/zqxvC6JwIDFEBk4bRtpSCR3AKZxR4jse9QyJ6i2woAS1MOiAG1+JQ83xZGemCOKGMMV9Z3MbJRM
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: influxdb-secrets
      namespace: monitoring
    type: Opaque
