apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: monitoring
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
