apiVersion: batch/v1
kind: CronJob
metadata:
  name: influxdb-backup
  namespace: monitoring
spec:
  schedule: "0 15 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: influxdb-backup
            image: influxdb:2.7.11-alpine
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "Starting backup at $(date)"
              influx backup /mnt/backup/influxdb-$(date +%Y%m%d%H%M%S) --host https://influxdb.${DOMAIN} --token "${INFLUXDB_OPERATOR_TOKEN}"
              echo "Backup completed at $(date)"

              echo "Removing backups older than 3 days..."
              find /mnt/backup -maxdepth 1 -mtime +3 -delete
            env:
            - name: INFLUXDB_OPERATOR_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: admin-token
            volumeMounts:
            - name: backup
              mountPath: /mnt/backup
          restartPolicy: OnFailure
          volumes:
          - name: backup
            nfs:
              server: ${NFS_SERVER}
              path: /volume1/kubernetes/backup/influxdb
          tolerations:
          - key: "role"
            operator: "Equal"
            value: "node-s"
            effect: "NoSchedule"
