#!/bin/bash

set -eu

dry_run_mode="none"

while getopts "d" flag; do
    case $flag in
    d)
        echo "Running dry-run mode..."
        dry_run_mode="server"
        ;;
    \?)
        echo "Wrong argument"
        exit 1
        ;;
    esac
done

# Add helm repositories
helm repo add crowdsec https://crowdsecurity.github.io/helm-charts && \
    helm repo add grafana https://grafana.github.io/helm-charts && \
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && \
    helm repo update

# Install prometheus crds
if ! kubectl get crd | grep -q monitoring.coreos.com; then
    echo -e "\nInstalling Prometheus CRDs..."
    kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
    kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
else
    echo -e "\nPrometheus CRDs already installed."
fi

project_path="$(git rev-parse --show-toplevel)"

# Deploy namespace
kubectl apply -f "${project_path}"/common/00-namespace.yaml

# Deploy common resources
kubectl apply -f "${project_path}"/common --dry-run="${dry_run_mode}"

# Deploy datasources

# prometheus
echo -e "\nDeploying prometheus..."
prometheus_dir="${project_path}/prometheus"

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade prometheus prometheus-community/prometheus --install --namespace monitoring --values "${prometheus_dir}"/helm/values.yaml --skip-crds --dry-run="server"
else
    helm upgrade prometheus prometheus-community/prometheus --install --namespace monitoring --values "${prometheus_dir}"/helm/values.yaml --skip-crds
fi

echo -e "Done!\n"

# loki
echo -e "\nDeploying loki..."
loki_dir="${project_path}/loki"

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade loki grafana/loki --install --namespace monitoring --values "${loki_dir}"/values.yaml --dry-run="server"
else
    helm upgrade loki grafana/loki --install --namespace monitoring --values "${loki_dir}"/values.yaml
fi

echo -e "Done!\n"

# alloy
echo -e "\nDeploying alloy..."
alloy_dir="${project_path}/alloy"

# Replace env variables
envsubst <"${alloy_dir}"/values.yaml | sponge "${alloy_dir}"/values.yaml

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade alloy grafana/alloy --install --namespace monitoring --values "${alloy_dir}"/values.yaml --dry-run="server"
else
    helm upgrade alloy grafana/alloy --install --namespace monitoring --values "${alloy_dir}"/values.yaml
fi

echo -e "Done!\n"

# grafana
echo -e "\nDeploying grafana..."
grafana_dir="${project_path}/grafana"

# Replace env variables
envsubst '${DOMAIN}' <"${grafana_dir}"/01-config-map.yaml | sponge "${grafana_dir}"/01-config-map.yaml
envsubst <"${grafana_dir}"/04-ingress-route.yaml | sponge "${grafana_dir}"/04-ingress-route.yaml

kubectl -n monitoring delete configmap grafana-dashboards --ignore-not-found=true
kubectl -n monitoring create configmap grafana-dashboards --from-file="${grafana_dir}"/dashboards --dry-run="${dry_run_mode}"

kubectl apply -f "${grafana_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# crowdsec
echo -e "\nDeploying crowdsec..."
crowdsec_dir="${project_path}/crowdsec"

kubectl apply -f "${crowdsec_dir}" --dry-run="${dry_run_mode}"

envsubst <"${crowdsec_dir}"/helm/values.yaml | sponge "${crowdsec_dir}"/helm/values.yaml

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade crowdsec crowdsec/crowdsec --install --namespace monitoring --values "${crowdsec_dir}"/helm/values.yaml --dry-run="server"
else
    helm upgrade crowdsec crowdsec/crowdsec --install --namespace monitoring --values "${crowdsec_dir}"/helm/values.yaml
fi

echo -e "Done!\n"
