#!/bin/bash

set -eu

dry_run_mode="none"

while getopts "d" flag; do
    case $flag in
    d)
        echo "Running dry-run mode..."
        dry_run_mode="server"
        ;;
    \?)
        echo "Wrong argument"
        exit 1
        ;;
    esac
done

# Add helm repositories
helm repo add influxdata https://helm.influxdata.com/ && \
    helm repo add crowdsec https://crowdsecurity.github.io/helm-charts && \
    helm repo add grafana https://grafana.github.io/helm-charts && \
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && \
    helm repo update

project_path="$(git rev-parse --show-toplevel)"

# Deploy namespace
kubectl apply -f "${project_path}"/common/00-namespace.yaml

# Deploy common resources
kubectl apply -f "${project_path}"/common --dry-run="${dry_run_mode}"

# prometheus
echo -e "\nDeploying prometheus..."
prometheus_dir="${project_path}/prometheus"

kubectl apply -f "${prometheus_dir}" --dry-run="${dry_run_mode}"

# Replace env variables
envsubst <"${prometheus_dir}"/helm/values.yaml | sponge "${prometheus_dir}"/helm/values.yaml

if ! helm status prometheus -n monitoring; then
    helm install prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --values "${prometheus_dir}"/helm/values.yaml
else
    if [[ "${dry_run_mode}" == "none" ]]; then
        helm upgrade prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --values "${prometheus_dir}"/helm/values.yaml --dry-run="server"
    else
        helm upgrade prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring --values "${prometheus_dir}"/helm/values.yaml
    fi
fi

echo -e "Done!\n"

# crowdsec
echo -e "\nDeploying crowdsec..."
crowdsec_dir="${project_path}/crowdsec"

kubectl apply -f "${crowdsec_dir}" --dry-run="${dry_run_mode}"

envsubst <"${crowdsec_dir}"/helm/values.yaml | sponge "${crowdsec_dir}"/helm/values.yaml

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade crowdsec crowdsec/crowdsec --install --namespace monitoring --values "${crowdsec_dir}"/helm/values.yaml --dry-run="server"
else
    helm upgrade crowdsec crowdsec/crowdsec --install --namespace monitoring --values "${crowdsec_dir}"/helm/values.yaml
fi

echo -e "Done!\n"

# Grafana
echo -e "\nDeploying Grafana..."
grafana_dir="${project_path}/grafana"

# Replace env variables
envsubst '${DOMAIN}' <"${grafana_dir}"/01-config-map.yaml | sponge "${grafana_dir}"/01-config-map.yaml
envsubst <"${grafana_dir}"/04-ingress-route.yaml | sponge "${grafana_dir}"/04-ingress-route.yaml

kubectl -n monitoring delete configmap grafana-dashboards --ignore-not-found=true
kubectl -n monitoring create configmap grafana-dashboards --from-file="${grafana_dir}"/dashboards --dry-run="${dry_run_mode}"

kubectl apply -f "${grafana_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# Loki
echo -e "\nDeploying Loki..."
loki_dir="${project_path}/loki"

# Replace env variables
envsubst <"${loki_dir}"/values.yaml | sponge "${loki_dir}"/values.yaml

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade loki grafana/loki --install --namespace monitoring --values "${loki_dir}"/values.yaml --dry-run="server"
else
    helm upgrade loki grafana/loki --install --namespace monitoring --values "${loki_dir}"/values.yaml
fi

echo -e "Done!\n"

# Alloy
echo -e "\nDeploying Alloy..."
alloy_dir="${project_path}/alloy"

# Replace env variables
envsubst <"${alloy_dir}"/values.yaml | sponge "${alloy_dir}"/values.yaml

if [[ "${dry_run_mode}" == "server" ]]; then
    helm upgrade alloy grafana/alloy --install --namespace monitoring --values "${alloy_dir}"/values.yaml --dry-run="server"
else
    helm upgrade alloy grafana/alloy --install --namespace monitoring --values "${alloy_dir}"/values.yaml
fi

echo -e "Done!\n"
