#!/bin/bash

set -e

sign_secret() {
    local cert_file=$1
    local input_secret=$2
    local output_secret=$3
    local namespace=$4
    
    sealed_secret="$(kubeseal \
        --cert "${cert_file}" \
        --format yaml \
        --scope namespace-wide \
        --namespace "${namespace}" \
        < "${input_secret}")"
    
    echo "${sealed_secret}" > "${output_secret}"
}

project_path="$(git rev-parse --show-toplevel)"
namespace="monitoring"

cert_file=$1

if [[ ! -f "${cert_file}" ]]; then
    echo "[!] Certificate ${CERT_FILE} not found!"
    exit 1
fi

echo "🔐 Signing secrets for namespace: '${namespace}'..."

# influxdb
input_secret="${project_path}/influxdb/00-secret.plain.yaml"
output_secret="${project_path}/influxdb/00-secret.yaml"
sign_secret "${cert_file}" "${input_secret}" "${output_secret}" "${namespace}"

# telegraf-nfs1
input_secret="${project_path}/telegraf-nfs1/00-secret.plain.yaml"
output_secret="${project_path}/telegraf-nfs1/00-secret.yaml"
sign_secret "${cert_file}" "${input_secret}" "${output_secret}" "${namespace}"

echo "[+] Sealed secret created for influxdb and telegraf-nfs1"
