---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: crowdsec-secrets
  namespace: monitoring
spec:
  encryptedData:
    ENROLL_KEY: AgB598sz2p2JaSK/MFe9NOrAhPIW1+8DSTH0+Y1Avh4qC7ZiSm8o+xpXnBbr4k7XRJqaUP0nBgTgTUhPEC7V6NV7XIQr97MVdjyzFzkC2oR9XZJWF12NfNq09ky3aPuWL9CX3MkkshVAwwZE6z5afcql987JclGUohW9HJpVpjfXHVm9k7hDBUQNAUrA1yXz4HemyGslj85JJIEVdM5BKMZglwc5KWFR/h3oo/j3gZFrPhcmcoKj0two8tinD1dMlMKMBSLiLEegtV/PmLJHZAVbzYqfBTJxONj6p+StfwLDO7WGr8YW1MK413IWPRenVrxiXedJL22WalhQHujPWkjih3UZeDtTSY9zmo7xVPkUnWhIqv6RqZ1pA7NqcIhtfgZ8bOzX3KIvgCe4g+ASowYUCz1KnRpwC2l7t13+n459dhnAde5tAOrFY6UcUpX05nyTc/m+8Ch2Dq/HwMshFZVdiDS1c/cf6yiZNfe+mSfZkPLBxYradiQeY0PbUQfYo1gaXqWakTj1VtyG/OS74Iee7OwSdP+cPy90Lj3ClWp1JV5Fx8fiSRvHWoTCGQz9PoS3eyhqyFR7mhvxDS5wObcUjM6I0uOx23Dx3ei9PSZfCzZzzcxiIzX4WxbwYnK4GyX+JyuCi8UB1d4DXw8+/80zkVFHxwCvHdAU2q5XQ32ObzLkiPb/FaBRTFRX//fMSFk=
    MB_ADMIN_EMAIL: AgBnczLPRT1N81itufjbq40CvaqPHHjp82E2rdPBIPBNQStn7b/cTuHwMWRElTBCI/3LZuQs2RilR/0aN7s5x2EVeb79FlPDcssC+w2FTjpoXXkLNHr44W0n3KG7o0Iu+zjoPY/UrQW8iq3rKTBLmBYLcx7z+aRElMHvxDidNtxULeiYO5KAdrMJ9cle3LI3WJVAja50NXLSdRnrTHzJWSKsdHpxHvBpnYwCMIKQ6vQFi4t1nW9ArAqhXvBOq05w8aLxD40IjMDqA/iT5/oAfo3E7kZn9YW8JBP2hUaCAcNRbdJ+c+w5/EEXplqpv+LcMr+GR1WNQ6mPDA7hCnZUUBPsZHRzGgdH86bgTC/CwEzcNnuZ/BZ2QpVBHRHGlZUr1ZiwB+8MgPwfC2vN18ZUTuDjP99NOgvC+92un4lH6++JEJPVvm9kaAQBM4OPwCChqSJt+h4SdQvfLGIqAdIFmfLm9RcxcWhX9D+1yhl8yvl1hpxzbMMpa9EP9z7a/4ZaZtinnRUwJvr9+KW+848EbaBubBDXKHO2gwaWGnZ7aPpDl1u2ZXaRfyivFmEEmf04hWbjDleQBt6SzEQ+PLPCpqCDAdF/D7eWllwg6HZGt48UdDphgYiW15jGTNJkRA8jXNP9vvux63mwIAciSfOjIcqVdVNpNbWKC/yn9SiTr/eP0HM11gk2cQ5B3jEF+XxUe7WTF6OASTzEYukFUL8DYNnPaw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: crowdsec-secrets
      namespace: monitoring
    type: Opaque
