# for raw logs format: json or cri (docker|containerd)
container_runtime: containerd
tls:
  enabled: true
  bouncer:
    reflector:
      namespaces: ["network"]
agent:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "cp"
    effect: "NoSchedule"
  # Specify each pod whose logs you want to process
  acquisition:
  # The namespace where the pod is located
  - namespace: network
    # The pod name
    podName: traefik-*
    # as in crowdsec configuration, we need to specify the program name to find a matching parser
    program: traefik
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  env:
  - name: COLLECTIONS
    value: "crowdsecurity/traefik"
  extraInitContainers:
  - name: wait-lapi
    image: busybox:1.35.0
    command:
    - sh
    - -c
    - |
      echo "[INFO] Waiting for LAPI..."
      for i in $(seq 1 60); do
        wget -q --spider http://crowdsec-service:8080/ || curl -sf http://crowdsec-service:8080/ && exit 0
        echo "LAPI not yet available ($i/60)..."
        sleep 5
      done
      echo "Error: LAPI did not become available in time."
      exit 1
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 100Mi

lapi:
  enabled: true
  persistentVolume:
    data:
      enabled: true
      storageClassName: nfs-sc
      size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  nodeSelector:
    size: m
